#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
export BUILDRUN_ENV_SH_LOADED_runtime=1

buildrun_env_vars=(
    AWS_REGION
    AWS_SECRET_ID
    BUILDING_DIR
    BUILDRUN_RUNTIME_APP_ID
    BUILDRUN_RUNTIME_APP_NAME
    BUILDRUN_RUNTIME_BASE_PATH
    BUILDRUN_RUNTIME_BUILDING_COMMAND
    BUILDRUN_RUNTIME_RUNING_COMMAND
    BUILDRUN_RUNTIME_DTRACK_API_KEY
    BUILDRUN_RUNTIME_DTRACK_HOST
    BUILDRUN_RUNTIME_ENTRYPOINT
    BUILDRUN_RUNTIME_ENVIRONMENT
    BUILDRUN_RUNTIME_ENVIRONMENT_LOWERCASE
    BUILDRUN_RUNTIME_ENVIRONMENT_UPPERCASE
    BUILDRUN_RUNTIME_ENVIRONMENT_UPPERCASE_FIRST
    BUILDRUN_RUNTIME_GITLEAK_SCANNER
    BUILDRUN_RUNTIME_GIT_REPO_URL
    BUILDRUN_RUNTIME_GIT_REPO_REVISION
    BUILDRUN_RUNTIME_JAVA_REPO_ID_PLACEHOLDER
    BUILDRUN_RUNTIME_JAVA_REPO_ID
    BUILDRUN_RUNTIME_JAVA_REPO_PASSWORD_PLACEHOLDER
    BUILDRUN_RUNTIME_JAVA_REPO_PASSWORD
    BUILDRUN_RUNTIME_JAVA_REPO_USER_PLACEHOLDER
    BUILDRUN_RUNTIME_JAVA_REPO_USER
    BUILDRUN_RUNTIME_JAVA_SETTING_LOCATION
    BUILDRUN_RUNTIME_NAMESPACE
    BUILDRUN_RUNTIME_CLUSTER_NAME
    BUILDRUN_RUNTIME_ORIGINAL_REGION
    BUILDRUN_RUNTIME_PORT
    BUILDRUN_RUNTIME_PUBLISHED_DIR
    BUILDRUN_RUNTIME_REGION
    BUILDRUN_RUNTIME_SECRET_ID
    BUILDRUN_RUNTIME_SECRETS_SCAN
    BUILDRUN_RUNTIME_SONAR_HOST_URL
    BUILDRUN_RUNTIME_SONAR_TOKEN
    BUILDRUN_RUNTIME_TRIVY_FORMAT
    BUILDRUN_RUNTIME_TRIVY_SCANNERS
    BUILDRUN_RUNTIME_VENV_HOME
    BUILDRUN_RUNTIME_MSSQL_TOOLS18_HOME
    BUILDRUN_RUNTIME_LANGUAGE
    BUILDRUN_RUNTIME_LANGUAGE_VERSION
    BUILDRUN_RUNTIME_IMAGE
    BUILDRUN_RUNTIME_USAGE
    BUILDRUN_RUNTIME_USAGE_TYPE
    BUILDRUN_RUNTIME_APM_ENABLED
    BUILDRUN_RUNTIME_WORK_DIR

    NEW_RELIC_LICENSE_KEY
    NEW_RELIC_APP_NAME
    NEW_RELIC_ENABLED
    NEW_RELIC_LABELS
    NEW_RELIC_LOG_FILE_NAME

    CORECLR_ENABLE_PROFILING
    CORECLR_PROFILER
    CORECLR_PROFILER_PATH
    CORECLR_NEWRELIC_HOME

    SW_AGENT_NAME
    SW_AGENT_NAMESPACE
    SW_AGENT_CLUSTER
    SW_AGENT_INSTANCE_NAME
    SW_AGENT_ENABLE
    SW_AGENT_COLLECTOR_BACKEND_SERVICES
    SW_AGENT_COLLECTOR_GRPC_UPSTREAM_TIMEOUT
    SW_AGENT_LOGGING_LEVEL
    ASPNETCORE_HOSTINGSTARTUPASSEMBLIES
)

for env_var in "${buildrun_env_vars[@]}"; do
    env_var_val=""
    if [[ -v "$env_var" ]]; then
        env_var_val=${!env_var}
        if [[ $env_var_val == "buildrun_nil" ]]; then
            env_var_val=""
        fi
    fi
    export $env_var="${env_var_val}"
done

unset env_var_val
unset buildrun_env_vars

declare -A default_value_env_vars

default_value_env_vars["BUILDRUN_SYSTEM_ROOT_DIR"]=${BUILDRUN_SYSTEM_ROOT_DIR:-/opt/buildrun}
default_value_env_vars["BUILDRUN_RUNTIME_DOTNET_TOOLS_BIN_DIR"]=${BUILDRUN_RUNTIME_DOTNET_TOOLS_BIN_DIR:-/root/.dotnet/tools}
default_value_env_vars["BUILDRUN_RUNTIME_MSSQL_TOOLS18_BIN_DIR"]=${BUILDRUN_RUNTIME_MSSQL_TOOLS18_BIN_DIR:-/opt/mssql-tools18/bin}
default_value_env_vars["BUILDRUN_SYSTEM_BIN_DIR"]=${BUILDRUN_SYSTEM_BIN_DIR:-${default_value_env_vars["BUILDRUN_SYSTEM_ROOT_DIR"]}/bin}
default_value_env_vars["BUILDRUN_SYSTEM_COMMON_BIN_DIR"]=${BUILDRUN_SYSTEM_COMMON_BIN_DIR:-${default_value_env_vars["BUILDRUN_SYSTEM_ROOT_DIR"]}/common/bin}
default_value_env_vars["BUILDRUN_SYSTEM_SCRIPT_DIR"]=${BUILDRUN_SYSTEM_SCRIPT_DIR:-${default_value_env_vars["BUILDRUN_SYSTEM_ROOT_DIR"]}/scripts}
default_value_env_vars["BUILDRUN_SYSTEM_TMP_DIR"]=${BUILDRUN_SYSTEM_TMP_DIR:-${default_value_env_vars["BUILDRUN_SYSTEM_ROOT_DIR"]}/tmp}
default_value_env_vars["BUILDRUN_SYSTEM_CONF_DIR"]=${BUILDRUN_SYSTEM_CONF_DIR:-${default_value_env_vars["BUILDRUN_SYSTEM_ROOT_DIR"]}/conf}
default_value_env_vars["BUILDRUN_RUNTIME_JAVA_SETTING_LOCATION"]=${BUILDRUN_RUNTIME_JAVA_SETTING_LOCATION:-${default_value_env_vars["BUILDRUN_SYSTEM_CONF_DIR"]}/maven/settings.xml}
default_value_env_vars["BUILDRUN_RUNTIME_HOME_DIR"]=${BUILDRUN_RUNTIME_HOME_DIR:-/buildrun/app}
default_value_env_vars["BUILDRUN_RUNTIME_VENV_ROOT_DIR"]=${BUILDRUN_RUNTIME_VENV_ROOT_DIR:-/buildrun/app/venv}
default_value_env_vars["BUILDRUN_RUNTIME_VENV_BIN_DIR"]=${BUILDRUN_RUNTIME_VENV_BIN_DIR:-${default_value_env_vars["BUILDRUN_RUNTIME_VENV_ROOT_DIR"]}/bin}
default_value_env_vars["BUILDRUN_RUNTIME_ENVIRONMENT_LOWERCASE"]=${BUILDRUN_RUNTIME_ENVIRONMENT_LOWERCASE:-${BUILDRUN_RUNTIME_ENVIRONMENT,,}}
default_value_env_vars["BUILDRUN_RUNTIME_ENVIRONMENT_UPPERCASE"]=${BUILDRUN_RUNTIME_ENVIRONMENT_UPPERCASE:-${BUILDRUN_RUNTIME_ENVIRONMENT^^}}
default_value_env_vars["BUILDRUN_RUNTIME_ENVIRONMENT_UPPERCASE_FIRST"]=${BUILDRUN_RUNTIME_ENVIRONMENT_UPPERCASE_FIRST:-${BUILDRUN_RUNTIME_ENVIRONMENT^}}

default_value_env_vars["CORECLR_ENABLE_PROFILING"]=${CORECLR_ENABLE_PROFILING:-0}
default_value_env_vars["CORECLR_PROFILER"]=${CORECLR_PROFILER:-{36032161-FFC0-4B61-B559-F6C5D41BAE5A}}
default_value_env_vars["CORECLR_PROFILER_PATH"]=${CORECLR_PROFILER_PATH:-${default_value_env_vars["BUILDRUN_RUNTIME_HOME_DIR"]}/newrelic/libNewRelicProfiler.so}
default_value_env_vars["CORECLR_NEWRELIC_HOME"]=${CORECLR_NEWRELIC_HOME:-${default_value_env_vars["BUILDRUN_RUNTIME_HOME_DIR"]}/newrelic}

default_value_env_vars["NEW_RELIC_ENABLED"]=${NEW_RELIC_ENABLED:-false}
default_value_env_vars["NEW_RELIC_LOG_FILE_NAME"]=${NEW_RELIC_LOG_FILE_NAME:-STDOUT}

default_value_env_vars["SW_AGENT_ENABLE"]=${SW_AGENT_ENABLE:-false}
default_value_env_vars["SW_LOGGING_OUTPUT"]=${SW_LOGGING_OUTPUT:-STDOUT}
default_value_env_vars["SW_AGENT_LOGGING_LEVEL"]=${SW_AGENT_LOGGING_LEVEL:-error}

for env_var_name in "${!default_value_env_vars[@]}"; do
    env_var_val="${default_value_env_vars[$env_var_name]-}"
    export $env_var_name="${env_var_val}"
    
    if [[ $env_var_name == *_BIN_* ]]; then
        PATH=$PATH:$env_var_val
    fi
done

unset env_var_val
unset default_value_env_vars

export PATH="${PATH}"
